### ISSUE TITLE
Request: Support for rolling back

### ISSUE THREAD

**Issue by crystalin** [AcalaNetwork/chopsticks#104]
Having the possibility to resume operation at a previous block could be a great feature (for testing mostly).
Ex:
- You generate few blocks to achieve a given state s0
- You run 1 test specific to that state
- you rollback to s0
- You run another test
- and ...

**Comment by ermalkaleci** [comment]
Yes we plan to do that

**Comment by ermalkaleci** [comment]
#21

**Comment by xlc** [comment]
closed as duplicate
