### ISSUE TITLE
Inccorectly handling request ending/closure

### ISSUE THREAD

**Issue by crystalin** [AcalaNetwork/chopsticks#144]
I didn't have time to dig into it yet.

When sending a tx to the node (with jsonrpc tools or polkadotjs) the clients usually stay hanging even after the block is produced with the tx.

Ex: `npx jaysonic -c ws -i localhost -p 8000 --method dev_newBlock --params '[]'` => 
```
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32000,
    "message": "Request Timeout"
  },
  "id": 1
}
```

**Comment by ermalkaleci** [comment]
@crystalin which chain?

**Comment by ermalkaleci** [comment]
polkadot.js/app works fine
try this
<img width="899" alt="Screenshot 2023-01-17 at 2 56 59 PM" src="https://user-images.githubusercontent.com/3055344/212917436-38cd3531-0cba-4580-923e-d64b5e00c9f1.png">

**Comment by ermalkaleci** [comment]
@crystalin update on this issue? I'm closing it if it's resolved
