### ISSUE TITLE
[Request] Embedding config in the script to allow `npx`

### ISSUE THREAD

**Issue by crystalin** [AcalaNetwork/chopsticks#161]
I didn't find a good way to support starting chopsticks (without cloning it) directly with `npx` as it requires to reference to the config file.

**Comment by ermalkaleci** [comment]
create a config file and run `npx @acala-network/chopsticks@latest dev --config=karura.yml`

**Comment by ermalkaleci** [comment]
those configs are more for development testing

**Comment by crystalin** [comment]
yes that would work, the idea was more to re-use the config file already existing in chopsticks, so I can provide directly the `npx ...` without telling people to also copy the file first

**Comment by ermalkaleci** [comment]
it's very unlikely you need that config. If you just want to start a node just provide `--endpoint` `npx @acala-network/chopsticks@latest dev --endpoint wss://kusama-rpc.polkadot.io`
Config is helpful for more advanced setup

**Comment by crystalin** [comment]
The config contains some useful features, more specifically the fact Alith has tokens and controls the sudo/council/....

**Comment by ermalkaleci** [comment]
still this is just one case when you need it.
But we can do is make config to accept url as well like genesis-provider so you either provider a file path or url to config

**Comment by crystalin** [comment]
Yes, I think that it is a more useful feature
