### ISSUE TITLE
Question: Is it possible to Time-Travel?

### ISSUE THREAD

**Issue by darwinsubramaniam** [AcalaNetwork/chopsticks#177]
I am trying out Chopsticks to implement some testing on the subquery project. I was able to start the network using chopstick but , wanted to move forward to specify era . Example scenario , Unbond staking will take 28era . How do i fast-track 28days and test the Withdrawn event.

Please do let me know if it is possible?

**Comment by ermalkaleci** [comment]
you can override storage however you like at any point by using RPC `dev_setStorage`. it will be something like this
https://github.com/AcalaNetwork/chopsticks/blob/daed18049e9b0e365d58a1c1d3a6193ec2c8c69c/e2e/dev.test.ts#L27-L31

**Comment by ermalkaleci** [comment]
should be something like 
```
{ Staking: { CurrentEra: 1234 } }
```

**Comment by darwinsubramaniam** [comment]
@ermalkaleci  Thanks , that helped :)
