### ISSUE TITLE
Migration not running until a tx is made

### ISSUE THREAD

**Issue by sander2** [AcalaNetwork/chopsticks#198]
When supplying a `wasm-override`, no migrations are run until you submit a tx. In hindsight, I guess that makes sense since no blocks are being added automatically. Still, I did expect the migration to have been run already. 

As a side note, if the migration accesses a lot of storage (and there is significant latency), then the tx will appear to freeze. In my case the first tx took ~30 minutes to complete, but I guess there's not much that can be done about that

**Comment by ermalkaleci** [comment]
wasm-override just replaces wasm to be used by future block, it's not meat to perform upgrade. If you want to perform upgrade you can sudo authorizeUpgrade 1st block and then sudo setCode 2nd block and on 3rd block it will perform the upgrade. You might also want to limit the storage either be removing some prefixes https://github.com/AcalaNetwork/chopsticks/blob/f57d89fc862b08dac0391a6d68e52164bbeba6cc/configs/kusama.yml#L27 or predefine a storage that is similar to what your testing, see import-storage

**Comment by xlc** [comment]
close as don't really see any changes to make
