### ISSUE TITLE
Incompatible with 0.9.38: invalid host configuration in relay chain state proof: Config(Absent) 

### ISSUE THREAD

**Issue by timbrinded** [AcalaNetwork/chopsticks#203]
When using chopsticks against Parachains connected to `0.9.38` relaychains, the following error happens when a `dev_newBlock` command is issued:

```
[09:58:41.845] INFO (rpc/34975): Westmint RPC listening on port 8000
[09:58:51.216] WARN (block-builder/34975): Failed to apply inherents {} Error: Error while executing Wasm VM: Trap: Unreachable
"panicked at 'Invalid host configuration in relay chain state proof: Config(Absent)', /build/pallets/parachain-system/src/lib.rs:405:31"
[09:58:51.216] INFO (ws/34975): Error handling request: Error: Error: Failed to apply inherents 'Error: Error: Failed to apply inherents
    at /tmp/xfs-c50dd874/dlx-34887/node_modules/@acala-network/chopsticks/dist/rpc/dev.js:19:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async dev_newBlock (/tmp/xfs-c50dd874/dlx-34887/node_modules/@acala-network/chopsticks/dist/rpc/dev.js:18:27)
    at async WebSocket.<anonymous> (/tmp/xfs-c50dd874/dlx-34887/node_modules/@acala-network/chopsticks/dist/server.js:131:30)
```

Tested against both Moonbase-Alpha and Westmint

----------------------
Example config:

```
endpoint: wss://westmint-rpc.polkadot.io
mock-signature-host: true

db: ./db.sqlite

import-storage:
  System:
    Account:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - data:
            free: '10000000000000000000'

```

**Comment by ermalkaleci** [comment]
Westmint seems to have some breaking changes with smoldot. Statemint working fine. Moonbase-alpha is failing for different reason RPC state_getKeysPagedAt missing. I'm think to refactor to just use  `state_getKeysPaged`

**Comment by timbrinded** [comment]
Looks like same issue to me. The common thing both westmint and moonbase have is they are connected to relay chains running 0.9.38

![image](https://user-images.githubusercontent.com/79199034/220642482-b2cfedbc-1937-4a79-8438-900afa66c77e.png)

**Comment by ermalkaleci** [comment]
Ok this is weird
`yarn start dev --endpoint wss://westmint-rpc.polkadot.io --block 3926941` works `3926942` doesn't work

**Comment by timbrinded** [comment]
Block 3926942 is when relay chain (westend) switches to `0.9.38` 🙂

**Comment by ermalkaleci** [comment]
I see, so basically V3 isn't working

**Comment by ermalkaleci** [comment]
smoldot doesn't support trie_version 1 yet  https://github.com/smol-dot/smoldot/issues/221

**Comment by ermalkaleci** [comment]
@timbrinded I got it working with 0.9.38. Westend still doesn't work because smoldot hasn't impl ext_storage_root_version_2 yet but parachain seems work. If you have tests please give it a try
