### ISSUE TITLE
[Question]  Node logs on chopistics Tx execution?

### ISSUE THREAD

**Issue by goncer** [AcalaNetwork/chopsticks#221]
Hi ! 
I would like to thank you for this tool, is amazing! :). Right now its a super helpful tool to debug user issues on the production environment! :muscle: 
I would like to ask if there is a way or getting node logs. For example, whenever A tx runs in the node, we have some logs, 
![image](https://user-images.githubusercontent.com/15139384/222669959-7bc758db-4aad-4c4f-93f6-52af272ba27c.png)

Would it be possible to have them while running chopsticks Tx? 
Thanks :hugs:

**Comment by ermalkaleci** [comment]
Thank you. It depends on smoldot how it implements host function. Will check it and let you know

**Comment by ermalkaleci** [comment]
yes it's possible to get runtime logs from smoldot so this feature can be implemented

**Comment by ermalkaleci** [comment]
no it's fine. Will close it when we implement the feature
