### ISSUE TITLE
UMP not working on kusama

### ISSUE THREAD

**Issue by sander2** [AcalaNetwork/chopsticks#243]
https://github.com/AcalaNetwork/chopsticks/pull/242 contains a fix for ump, but for me that's only working for older blocks. On the chain head (i.e. not providing a block number in the config), messages do not get delivered to the kusama chain.

There seems to be some randomness involved. On older blocks, it works.. sometimes. Once it works, it seems to keep working, but otherwise a chopsticks restart sometimes helps. One thing I noticed, is that sometimes, a block containing the xtokens.transfer call gets included on the parachain side, but on the relay chain side no block gets mined until an additional block on the parachain is mined.

**Comment by ermalkaleci** [comment]
For kusama it's best using import-storage with some clearPrefix (checkout configs/kusama.yml) otherwise it will keep pulling a lot of storage and never build any block

**Comment by ermalkaleci** [comment]
Also define a db for caching

**Comment by sander2** [comment]
Thanks for the tip - turns out that it kept querying `parasDisputes.disputes` - probably due to this issue that's going on right now on kusama: https://twitter.com/dev0_sik/status/1634160837110661122?s=61&t=lrlpzqvaD2VRuynGgaR0aQ

Clearing that prefix fixed it
