### ISSUE TITLE
how can set default for block: ${env.PICASSO_BLOCK_NUMBER}?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [AcalaNetwork/chopsticks#260]
for example, 

```yaml
block: ${env.PICASSO_BLOCK_NUMBER:-42}
```
how it is in bash.

**Comment by xlc** [comment]
we using `_.template` to process the config file https://lodash.com/docs/4.17.15#template

https://github.com/AcalaNetwork/chopsticks/blob/b2d9b7dc3907e3c963b70f6e096e80521ae6ae2c/packages/chopsticks/src/cli.ts#L28
