### ISSUE TITLE
Only one UMP message processed per block

### ISSUE THREAD

**Issue by sander2** [AcalaNetwork/chopsticks#293]
When sending multiple xcm messages in the same block to the relay chain, only a single one is immediately produced. The second only gets processed after you manually trigger the production of another block on the relay chain

**Comment by ermalkaleci** [comment]
depends how are you sending multiple xcm messages and block-mode configuration. If block-mode is instant then it will start building new block as soon as receiving first tx. so you can either start with block-mode manually and trigger block build manually or switch block-mode to manual, submit your txs then switch back to instant and after that either trigger a new block or send the last xcm msg to trigger block building

**Comment by sander2** [comment]
> depends how are you sending multiple xcm messages and block-mode configuration. If block-mode is instant then it will start building new block as soon as receiving first tx. so you can either start with block-mode manually and trigger block build manually or switch block-mode to manual, submit your txs then switch back to instant and after that either trigger a new block or send the last xcm msg to trigger block building

In my case, there was only a single tx, which was a batch containing two xcm transfers. Of course I can trigger an explicit production of an extra block on the relay chain, but ideally that shouldn't be needed

**Comment by ermalkaleci** [comment]
a single tx should work. can you post extrinsic and which chain so I can debug?

**Comment by sander2** [comment]
Sure, thanks for looking into it. I [uploaded](https://gist.github.com/sander2/c696ed693e1cade09783f2160d7a568a) the configs I used. The chains used are interlay + polkadot. The extrinsic that I used is `0x02000302085b0001010002140004000000000700f2052a0113000000000700f2052a010006000700e40b5402383c00ee070000e803000000900100140d01000400010100b853988cb73cb4b2f58d15910d2dba4b37656b0542c799fbe92ba133e14e86305b0001010002140004000000000700f2052a0113000000000700f2052a010006000700e40b5402183c01ee070000140d01000400010100b853988cb73cb4b2f58d15910d2dba4b37656b0542c799fbe92ba133e14e8630`, which you can execute as Alice.

**Comment by xlc** [comment]
I think we just need to improve the build block queue to debounce it a bit on instant mode

**Comment by xlc** [comment]
this is bug of Polkadot 9370 runtime. it can only process 1 ump per block. this is fixed in 9420 https://github.com/paritytech/polkadot/blob/645723987cf9662244be8faf4e9b63e8b9a1b3a3/runtime/polkadot/src/lib.rs#L1306
