### ISSUE TITLE
RPC availability

### ISSUE THREAD

**Issue by goncer** [AcalaNetwork/chopsticks#298]
Hello hello! 
In Mangata we are aiming to use chopsticks to speed up our e2e tests. Sadly I found that custom RPCs are not available when using chopsticks.  We have a not big/not small amount of rpcs 
![image](https://github.com/AcalaNetwork/chopsticks/assets/15139384/279a7d60-2148-4e0c-9b7e-50f0644ddc9d)
I`ve also tried adding them to the APIPromise param, but no luck. 

https://github.com/mangata-finance/mangata-e2e/pull/248/files#diff-61c0e1b3905edb6ef2907983f7581a0f791baf288d90de1ba24fc920e1022d7dR68

Do you know if there is /will be a way to support rpc somehow? 

Thanks for this awesome tool! :muscle:

**Comment by ermalkaleci** [comment]
Your PRCs are part of your client, not runtime. Chopsticks is a client that runs any runtime. So the answer is no, they cannot be part of chopsticks but you can access the runtime call if the entire logic is inside runtime or you can implement helpers for your tests

**Comment by xlc** [comment]
The proper solution is replace usage of custom rpc with state_call. Otherwise you dapp will not work with light clients as well.

**Comment by ermalkaleci** [comment]
@goncer I had a quick look at your repo https://github.com/mangata-finance/mangata-node/blob/926507a9a8b0f0179500da10855f404714b8374f/runtime/mangata-kusama/src/lib.rs#LL1869C24-L1869C30
and seems you can do a state_call to `XykApi_calculate_sell_price` with encoded parameters and then you need to decode output

**Comment by ermalkaleci** [comment]
@goncer this is an example from bodhi https://github.com/AcalaNetwork/bodhi.js/blob/38c2ec7ed76cafd89567d24fbd998074b0594b91/packages/eth-providers/src/base-provider.ts#L830C15-L831

**Comment by goncer** [comment]
Thanks for the answers  ! :hugs: 
I guess we can close the issue. 
I'll give it a try to state_call

**Comment by goncer** [comment]
state_call works! 
Leaving here some code for future requests.
https://github.com/mangata-finance/mangata-e2e/pull/248/files#diff-7646ebf18e272237de4892a24063cdce59209687622fcd93eac200a0e5e04756R8
