### ISSUE TITLE
latest kusama and statemine tx fails

### ISSUE THREAD

**Issue by ermalkaleci** [AcalaNetwork/chopsticks#299]

**Comment by goncer** [comment]
ups, we realized this too. 
In our tests, ~yday tests were ok, but now they start falling. Additionally kusama.yml references to Council storages that triggers an error. What we found so far (hopefully it helps ) :)  :  

XCM transfer ( from ksm to mangata )  fails with chops  with l&g block

The very same xcm transfer works correctly in the relay

Yday the tx worked in chops, and setting this block works simply ok. 

 KUSAMA_BLOCK_NUMBER=18049622 npx @acala-network/chopsticks@latest  xcm --parachain=configs/mangata.yml_chops  --relaychain=configs/kusama.yml

It looks like that Council pallet is not available on the l&g block, but works on block `18049622`

**Comment by ermalkaleci** [comment]
yes those pallets are removed but these another change in runtime making transaction validation to fail. investigating ...

**Comment by ermalkaleci** [comment]
found it, system::account needs to have providers

**Comment by ermalkaleci** [comment]
@goncer ^
