### ISSUE TITLE
Extrinsic RPC subscription events are capitalized

### ISSUE THREAD

**Issue by kratico** [AcalaNetwork/chopsticks#304]
This is inconsistent with the Polkadot RPC

In Polkadot the `ready`, `inBlock`, `finalized` subscription event keys are not capitalized

![image](https://github.com/AcalaNetwork/chopsticks/assets/1209171/1d5f9fd5-5aec-4101-bd0d-f7dc69c5cc27)

Using chopsticks these event keys are `Ready`, `InBlock`, `Finalized

![image](https://github.com/AcalaNetwork/chopsticks/assets/1209171/110942f2-642c-436e-9265-6e79ec8d5398)

**Comment by xlc** [comment]
I will put this as "won't fix" for now until one of those happens:
- Identify compatibility issue with existing tools due to this
- OR some spec is created specifying what's the correct behaviour

**Comment by jsdw** [comment]
There is no spec, but Substrate nodes and now Smoldot will return the non-capitalised event names, so shouldn't chopsticks align with these?

A compatibility issue at present is with Subxt, which understands the smoldot/substrate based camelCase event names and fails for the uppercase names emitted by chopsticks (Rust being more strict on these sorts of things).

**Comment by xlc** [comment]
we can fix this if it is causing trouble for subxt
