### ISSUE TITLE
Not support `state_getStorageAt` when replaying Polkadot Blocks

### ISSUE THREAD

**Issue by albertov19** [AcalaNetwork/chopsticks#345]
It seems that with the latest Chopsticks it is not supporting the new RPC method `state_getStorageAt` when  trying to replay a block - maybe this was introduced in 0.9.43?

**Comment by albertov19** [comment]
I've modified a Chopsticks fork and now I run into `state_getKeysPagedAt` so it seems that it also needs fixed

After forcing this:

```
  async getStorage(key: string, hash?: string) {
    return this.#provider.send<string>('state_getStorage', [key, hash])
  }

  async getKeysPaged(prefix: string, pageSize: number, startKey: string, hash?: string) {
    return this.#provider.send<string[]>('state_getKeysPaged', [prefix, pageSize, startKey, hash])
  }
  ```
  
  In `chopsticks/packages/chopsticks/src/api.ts` it worked

**Comment by xlc** [comment]
how do I repreoduce this issue?

**Comment by xlc** [comment]
but the `At` rpc is just alias so the current code is redundant anyway. will change it.

**Comment by albertov19** [comment]
Try replaying a Polkadot block now with 0.9.43 - not sure if it is when that RPC method changed but I could not replay it.

Thanks!

**Comment by xlc** [comment]
Could you try Chopsticks master and let me know if it fixed the issue for you?

**Comment by albertov19** [comment]
It worked! Thanks!!

**Comment by xlc** [comment]
We had a big refactor. Could you try `0.8.0-5`? It is currently marked as beta.
