### ISSUE TITLE
Persistent mode

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/chopsticks#347]
- [ ] Save chain/blocks to sqlite db
- [ ] Load chain from db
- [ ] Config to specify max number of blocks to be stored in memory. If db is enabled, save them to db before purge.

**Comment by qiweiii** [comment]
- [ ] Config to specify max number of blocks to be stored in memory.
  - background: problem is now all blocks are in memory, too many blocks will break the program.
  - [ ] stage 1: when exceed the max number of block, delete old blocks, so it won't break
  - [ ] stage 1: If db is enabled, save old blocks to db before purge
- [ ] Save chain/blocks to sqlite db before purge
- [ ] Load chain/blocks from db, and resume from where it stopped

**Comment by xlc** [comment]
No need to change build block mode. We still want this with all the existing modes.

**Comment by qiweiii** [comment]
updated
