### ISSUE TITLE
Erroneous execution of pallet-contracts

### ISSUE THREAD

**Issue by TorstenStueber** [AcalaNetwork/chopsticks#369]
Wasm smart contract execution via pallet-contracts seems to be erroneous when using chopsticks and the result of running a smart contract can be different when executing on the actual chain or on a chopsticks clone of the chain.

## How to reproduce
**Step 1**: First create a config file `foucoco.yml` for our testnet Foucoco (which runs on Rococo) with the following content:

```yml
endpoint: wss://rpc-foucoco.pendulumchain.tech
mock-signature-host: true
db: ./db.sqlite
```

**Step 2**: Start local fork of Foucoco:
```
npx @acala-network/chopsticks@latest --config foucoco.yml
```

**Step 3**: Register an existing contract on polkadot.js
Go to [polkadot.js](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc-foucoco.pendulumchain.tech#/contracts) of Foucoco, click on "Add an existing contract" and
* for "contract address" enter `6nNcCULGU2XNaz1f1NqvoLpBgzyZaLFyYMNUMSwYZqpmi5hc`
* for "contract abi" select a file with the following content
  ```
  {
    "contract": {
      "authors": [
        "unknown"
      ],
      "name": "Test",
      "version": "0.0.1"
    },
    "spec": {
      "messages": [
        {
          "args": [],
          "default": false,
          "docs": [
            ""
          ],
          "label": "test",
          "mutates": false,
          "payable": false,
          "returnType": {
            "displayName": [
              "ink_primitives",
              "types",
              "AccountId"
            ],
            "type": 2
          },
          "selector": "0xf887ea40"
        }
      ]
    },
    "types": [
      {
        "id": 0,
        "type": {
          "def": {
            "primitive": "u8"
          },
          "path": [
            "u8"
          ]
        }
      },
      {
        "id": 1,
        "type": {
          "def": {
            "array": {
              "len": 32,
              "type": 0
            }
          }
        }
      },
      {
        "id": 2,
        "type": {
          "def": {
            "composite": {
              "fields": [
                {
                  "type": 1
                }
              ]
            }
          },
          "path": [
            "ink_primitives",
            "types",
            "AccountId"
          ]
        }
      }
    ],
    "version": "4"
  }
  ```
**Step 4**: Run the `test` message
Once the contract is registered, choose the message `test` and "Read" it. It should return `6kSs4SHJCXbMhFrwgtaVBXvirDkUYrwLgocMdCZDvBswmn5H`

**Step 5**: Repeat steps 3 and 4 for the chopstick fork
Now go to [polkadot.js for the clone](https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A8000#/contracts) (or use a different port if required), register the same existing contract and read the `test` message. This time the result will just be `<empty>`

**Comment by xlc** [comment]
Contracts is using child trie, which is not fully supported yet. 
I just checked and looks like smoldot now have child trie support so we should be able to implement this.
