### ISSUE TITLE
QueryFailedError: SQLITE_CONSTRAINT: NOT NULL constraint failed: key_value_pair.blockHash

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/chopsticks#371]
yarn start --endpoint wss://karura-rpc.aca-staging.network/ws --block 999999999 `

getting error 

```
QueryFailedError: SQLITE_CONSTRAINT: NOT NULL constraint failed: key_value_pair.blockHash
    at Statement.handler (/Users/xiliangchen/projects/acala/chopsticks/src/driver/sqlite/SqliteQueryRunner.ts:113:26)
[ERROR] 10:34:15 QueryFailedError: SQLITE_CONSTRAINT: NOT NULL constraint failed: key_value_pair.blockHash
```

changes requires:

- [x] tests
- [x] error on invalid block number
- [x] ensure internal fatal error are propagated and actually crash the program
- [x] add few more assertions to detect bad parameters early

**Comment by xlc** [comment]
still need tests and other work

**Comment by ermalkaleci** [comment]
this was not sql issue. we're starting the chain with null blockHash
