### ISSUE TITLE
Doc generation

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/chopsticks#389]
after #388

setup tsdoc and deploy docs to gh page

**Comment by qiweiii** [comment]
Found a few tools for tsdoc doc generator
- [api-documenter](https://api-extractor.com/pages/setup/generating_docs/#using-api-documenter-to-generate-markdown)
- [typeDoc](https://github.com/TypeStrong/typedoc)

Some examples:
- TypeDoc: https://natoboram.gitlab.io/eldarya-enhancements/classes/Duration.html
- api-documenter: https://kristiandupont.github.io/extract-pg-schema/api/extract-pg-schema.extractschemas.html

Which one do you prefer @xlc @ermalkaleci

**Comment by xlc** [comment]
api-documenter looks better

**Comment by qiweiii** [comment]
I also prefer the second one's style, the style is actually from (vitepress)[https://vitepress.dev/], api-documenter only generate markdowns
