### ISSUE TITLE
Can't find eth rpc method

### ISSUE THREAD

**Issue by hqwangningbo** [AcalaNetwork/chopsticks#405]
@xlc  Currently , Chopsticks is not able to emulate the Rpc interface is it?
I started Moonbeam, but I can't find the eth interface, i.e. I can't send Ether transactions ?

<img width="885" alt="image" src="https://github.com/AcalaNetwork/chopsticks/assets/57781136/5bd9f5df-5469-4fb9-b2a7-16c0798d0dc9">

**Comment by hqwangningbo** [comment]
For Moonbeam, I want to test already deployed contracts, what should be the best way to do this?

**Comment by xlc** [comment]
only standard substrate RPC are supported and not including eth rpc
