### ISSUE TITLE
Runtime upgrade  migrations leaves some keys in storage

### ISSUE THREAD

**Issue by goncer** [AcalaNetwork/chopsticks#431]
Hey! 
I'm running a runtime upgrade, that triggers a migration.  Somehow it leaves some storage keys in the chainstate, while when running the nodes with parachain-launch, migrations look okay. 

![image](https://github.com/AcalaNetwork/chopsticks/assets/15139384/98c93337-2c87-44a7-878e-9fca492d07de)

How to reproduce: 

You can either create two versions of any parachain, with a migration ( hopefully gets reproduced )  

Or

You can run the test on the mangata-e2e repo. This test basically spawns two parachains, performs a runtime upgrade, and runs some xcms. 
 * Checkout this PR - code branch: https://github.com/mangata-finance/mangata-e2e/pull/328/files
 * nvm use 18.16.1
 * yarn
 * yarn test-xcm-ru-statemine 

Ping me if any q! 
thanks!

**Comment by xlc** [comment]
Likely some key handling needs an improvement.

**Comment by ermalkaleci** [comment]
@goncer can't reproduce this 
<img width="580" alt="Screenshot 2023-10-12 at 2 40 57 PM" src="https://github.com/AcalaNetwork/chopsticks/assets/3055344/0afd3743-69c1-4cd3-95fa-ae318f424bd0">

**Comment by goncer** [comment]
hey @ermalkaleci , 
Sorry, long weekend :) 

How are you running the test? 
I tried again, and works for me :o
Steps:

1. git checkout feature/improve-ru-xcm-tests
2. nvm use 18.16 
3. rm -rf node_modules && rm yarn.lock &&  yarn
4. yarn test-xcm-ru-statemine
It should take some time until the runtime applies, but after ~100s it will print some AssetRegistry info, and you will probably check on polkadotJs 3000 or 3001 port. 

:crossed_fingers:

**Comment by ermalkaleci** [comment]
@goncer I am following your steps and I still get the same error:
<img width="1066" alt="Screenshot 2023-10-23 at 10 13 33 PM" src="https://github.com/AcalaNetwork/chopsticks/assets/3055344/4cd5e969-863b-4140-bd1c-5e256d0cb93e">

**Comment by ermalkaleci** [comment]
I believe the problem is at this line https://github.com/mangata-finance/mangata-e2e/pull/328/files#diff-61c0e1b3905edb6ef2907983f7581a0f791baf288d90de1ba24fc920e1022d7dR145

**Comment by ermalkaleci** [comment]
got it running
<img width="835" alt="Screenshot 2023-10-23 at 10 30 35 PM" src="https://github.com/AcalaNetwork/chopsticks/assets/3055344/ea684665-5b94-4061-aa62-6246215152e9">

but I can't find any key ["25"] nor null value

**Comment by goncer** [comment]
omg, we run the runtime upgrade on Oct23, so that's the reason, the upgrade is already applied on Kusama, let me try to find the block before the runtime upgrade  and see if we can reproduce it :facepalm: 
Sorry for the late answer :(

**Comment by goncer** [comment]
@ermalkaleci  Pushed a script change that sets the block number way before the runtime upgrade. 
+ "test-xcm-ru-statemine": "export MANGATA_BLOCK_NUMBER=3469500  ` 
plz, get the latest and greatest. The issue must be reproducible now. 
Thanks for following this up! :clap:

**Comment by ermalkaleci** [comment]
ok reproduced

**Comment by goncer** [comment]
hey @ermalkaleci , 3469557!
https://mangatax.subscan.io/block/3469557?tab=event

**Comment by goncer** [comment]
:tada:
