### ISSUE TITLE
review usage of wasm / registry / metadata

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/chopsticks#494]
When execute a block, it should be using the parent wasm for execution.

This includes runtime calls etc.
https://github.com/AcalaNetwork/chopsticks/blob/6191b00a1533d54655e62f271261e0ce7e7e3b80/packages/core/src/blockchain/block.ts#L312

setWasm on a block shouldn't impact its execution result. but the next block.

Similarly, the registry should of current block should be using the metadata from parent block.

Needs to review all the usage of wasm/metadata/registry to ensure we are using the right one.

I think we need to rename wasm/metadata/registry to avoid ambiguity. Or make then internal and expose some better named methods.

**Comment by ermalkaleci** [comment]
I don't think this is an issue. It's already using parent wasm

**Comment by xlc** [comment]
This is mainly about review and make sure everything is good and if that's the case, we can close it
