### ISSUE TITLE
Don't implicit load plugins

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/chopsticks#512]
Add a method to load plugins and call it from the entrypoint.
We don't want to load then on import the files to avoid impact of start time on other applications using chopsticks as a library.

**Comment by ermalkaleci** [comment]
I think we worry about this when this becomes a problem

**Comment by ermalkaleci** [comment]
can't we just remove the logs?

**Comment by xlc** [comment]
Let's fix the problem, not the symptom
