### ISSUE TITLE
storage override needs to support storage value type of `()` 

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/chopsticks#515]
for example, `whitelist.whitelistdCall`

**Comment by qiweiii** [comment]
how do I reproduce this?

**Comment by xlc** [comment]
<img width="790" alt="Screenshot 2023-11-09 at 8 55 09 PM" src="https://github.com/AcalaNetwork/chopsticks/assets/1201310/6b46ca50-98d1-48da-91ea-327a475abb89">

this is on Polkadot. 

We need a way to use `dev_setStorage` to add and remove whitelistedCall entry. The value type is `()`, which is basically a `void` so we may need to distinguish null and undefined

**Comment by ermalkaleci** [comment]
@xlc just pass '0x' for empty values

```
Whitelist:
    WhitelistedCall:
      -
        -
          - '0xe284be84dcfaf714ef2b7717b54914632406f2c17d8203d3268e4c4ca68fa144'
        - 0x
```

**Comment by qiweiii** [comment]
Maybe we should add it in readme or in docs abt how to use these, so user knows
