### ISSUE TITLE
setHead stops working

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/chopsticks#516]
Just tried it with 0.9.0 and dev_setHead wasn't working for me

**Comment by ermalkaleci** [comment]
I tried. It seems to work

**Comment by xlc** [comment]
`npx @acala-network/chopsticks@0.9.0 xcm --relaychain kusama --parachain statemine --parachain kusama-bridge-hub`

and `api.rpc('dev_setHead', [-1])` in https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A8000#/js

**Comment by ermalkaleci** [comment]
you're sending [-1], should be -1

**Comment by xlc** [comment]
oh right I forget it adds the array for me. ok, but still, the error message is confusing.

I guess what's missing is z schema validation

**Comment by ermalkaleci** [comment]
yes
