### ISSUE TITLE
new package chopsticks-utils

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/chopsticks#534]
move all the code thats not related to `vitest` from testing to utils. I want to write some quick Chopsticks script ([example](https://github.com/xlc/chopsticks-ksm-xcm/tree/master)) without importing vitest

**Comment by ermalkaleci** [comment]
it's just a file. why not move it to chopsticks?

**Comment by xlc** [comment]
we will have more things there in future

**Comment by qiweiii** [comment]
Do we only want test related utils in this package? is so we could name it testing-utils

**Comment by xlc** [comment]
For example, to implement this https://github.com/polkadot-fellows/runtimes/issues/83, we need the ability to launch new networks on the fly to dry run the xcm on dest chain. This will be something can be implemented here and not just for testing.
