### ISSUE TITLE
Trying to send XCM to Kusama Asset Hub (fka. Statemine) fails

### ISSUE THREAD

**Issue by bvotteler** [AcalaNetwork/chopsticks#547]
Starting yesterday, I have been seeing errors when trying to send an XCM to statemine:

```
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "A node of the proof has an invalid format: Empty".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```
It seems to occur as chopsticks is trying to construct the block on statemine side.

----
Steps to replicate:
- place ymls from attached [configs.zip](https://github.com/AcalaNetwork/chopsticks/files/13374214/configs.zip) inside `configs/` (_edit_: replaced corrupted config in the zip)
- start chopsticks
```
yarn start xcm \
--relaychain=configs/kusama-minimal.yml \
--parachain=configs/kintsugi-minimal.yml \
--parachain=configs/statemine-minimal.yml
```
- submit extrinsic as Alice on kintsugi: `0x5e000103000000b0ad010000000000000000000000000003010200a10f0100da848c67aef561ae2a63fbe382a16eb82583f5377be6ddb5b10a72bf4050d82900` (raw), or
- alternatively, assuming kintsugi is running as localhost:8000, [this link](https://polkadot.js.org/apps/?rpc=ws%3A%2F%2Flocalhost%3A8000#/extrinsics/decode/0x5e000103000000b0ad010000000000000000000000000003010200a10f0100da848c67aef561ae2a63fbe382a16eb82583f5377be6ddb5b10a72bf4050d82900) should get you there faster.

**Comment by ermalkaleci** [comment]
try latest beta. we have done some fixes

**Comment by bvotteler** [comment]
> try latest beta. we have done some fixes

Which tag/branch should I use? For context, I'm seeing that issue on master.

**Comment by ermalkaleci** [comment]
@acala-network/chopsticks:0.9.2-6

**Comment by bvotteler** [comment]
> @acala-network/chopsticks:0.9.2-6

I'm afraid I'm seeing the same error after checking out `0.9.2-6`, rebuilding the project and running again.

**Comment by bvotteler** [comment]
And I'm also getting the same error when running
```
npx @acala-network/chopsticks@0.9.2-6 xcm \
-r configs/kusama-minimal.yml \
-p configs/kintsugi-minimal.yml \
-p configs/statemine-minimal.yml
```
(tried that to make sure I don't have some weirdness going on in my local builds)

**Comment by ermalkaleci** [comment]
ok it's another issue, investigating

**Comment by ermalkaleci** [comment]
https://github.com/smol-dot/smoldot/pull/1362

**Comment by ermalkaleci** [comment]
@bvotteler This was an issue for a range of blocks and it's working again
