### ISSUE TITLE
Event "isBroadcast" never fired

### ISSUE THREAD

**Issue by Tbaut** [AcalaNetwork/chopsticks#568]
To test my UI, I'm checking for Tx events. I have a code that looks like
```
api.tx.balances
  .transfer(recipient, 123)
  .signAndSend(sender, ({ status, events }) => {
    console.log(status)
 })
```
It goes from `isReady`, to `isInBlock` and `isFinalized` without the `isBroadcast`.

It's somewhat similar to https://github.com/AcalaNetwork/chopsticks/issues/434#issuecomment-1762958798

**Comment by ermalkaleci** [comment]
broadcast is chain thing, when tx is broadcasted to other chains. Chopsticks is a standalone simulator chain. This RPC is a simulation. If you really need it we can just fire it right after isReady

**Comment by ermalkaleci** [comment]
@Tbaut give this a try

**Comment by Tbaut** [comment]
Thanks Ermal, this is not published as a beta automatically is it? This would make things easier to test for me rather than master. I'll wait for the next beta release

**Comment by ermalkaleci** [comment]
@Tbaut releasing new beta

**Comment by Tbaut** [comment]
it's working well, thanks a lot!
