### ISSUE TITLE
Add sudo to a non-sudo chain

### ISSUE THREAD

**Issue by savudani8** [AcalaNetwork/chopsticks#57]
What would it take for this tool to add sudo privilleges even if the sudo pallet isn't included in the chain we are forking? The approach used by [fork-off-substrate](https://github.com/maxsam4/fork-off-substrate) was to download the current state as a chainspec and start a dev chain with it. In our case fork-off-substrate did not produce blocks so wasn't very useful.

**Comment by xlc** [comment]
It is not possible to automatically have this feature. You need to build a wasm runtime with sudo pallet and override the wasm runtime to the one with sudo pallet.
