### ISSUE TITLE
More than 30s to build a block on Kusama

### ISSUE THREAD

**Issue by Tbaut** [AcalaNetwork/chopsticks#588]
Hello there,

I'm running Chopsticks in Github CI, forking Kusama with the same [example config](https://github.com/AcalaNetwork/chopsticks/blob/master/configs/kusama.yml) that you have. Just with a couple more funded accounts.

However, it very often takes more than 30s to create a block in CI, although I would expect it to take only a couple seconds. E.g here it took 34s
```
 [16:20:51.742] INFO (block-builder/1744): Try building block #20,487,321
[16:21:25.637] INFO (block-builder/1744): Block built
    number: 20487321
    hash: "0xcd92210a07f5bbc9146070cd3f07f211acf168e647de9b60953341984b32d8cd"
    extrinsics: [
      "0x91038400fa8e003cb5d22db1e8658e05…34d00c4f001e04000000000000000000"
    ]
    pendingExtrinsicsCount: 0
    ump: {}
```

It takes locally ~20s

I've tried to comment out the line below `ParaDisputes` without changes
https://github.com/AcalaNetwork/chopsticks/blob/master/configs/kusama.yml#L54

any hint?

**Comment by ermalkaleci** [comment]
make sure to use an endpoint without rate limit or at least with high burst. chopsticks can build block within a second if has the storage but it depend on endpoint to pull the data, so that contributes to the delay
