### ISSUE TITLE
tests to ensure cli parsing code is correct

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/chopsticks#604]
so we can catch bug like https://github.com/AcalaNetwork/chopsticks/pull/603

**Comment by qiweiii** [comment]
I saw that we already have an [options.test.ts](https://github.com/AcalaNetwork/chopsticks/blob/d7b476eb44f14e8e88e39b2f263d9ccffe330c4f/packages/chopsticks/src/schema/options.test.ts), do we need more tests?

**Comment by xlc** [comment]
it doesn't catch the bug I introduced here https://github.com/AcalaNetwork/chopsticks/pull/636 so we need more
