### ISSUE TITLE
No DMP messages received in Parachain

### ISSUE THREAD

**Issue by NachoPal** [AcalaNetwork/chopsticks#631]
When running a Parachain from a genesis file, DMP messages are not received.

Block is built in the Parachain as a response of sending a XCM from the Relay Chain, but `parentHead` and `downwardMessages` in `setValidationData` are empty.

**Comment by ermalkaleci** [comment]
as I said last time, starting xcm with genesis won't work because you won't have any parachain registered

**Comment by NachoPal** [comment]
> as I said last time, starting xcm with genesis won't work because you won't have any parachain registered

I manually registered and onboarded before sending the message.

I could try to add it to the genesis state if you think that will make any difference.

**Comment by NachoPal** [comment]
I added the Parachain in the genesis file but same result.

I provide the chain spec
[chain-spec-with-para-v1.0.0.json](https://github.com/AcalaNetwork/chopsticks/files/13942204/chain-spec-with-para-v1.0.0.json)

**Comment by ermalkaleci** [comment]
the problem is missing `dmqMqcHead`, I will see if we can mock it

**Comment by ermalkaleci** [comment]
@NachoPal can you give this a try? #633

**Comment by ermalkaleci** [comment]
you don't need to do anything extra, just start from genesis

**Comment by NachoPal** [comment]
> the problem is missing dmqMqcHead, I will see if we can mock it

That was it, now it is working. Let you know that it is not even necessary to add the Parachain in genesis for XCM to work bidirectionally.

I do not know if you can foresee some side effects or something that might not work/malfunction if a Parachain is not registered.

**Comment by ermalkaleci** [comment]
Chopsticks intercepts xcm messages produced by runtime execution  and triggers block building on the other chain with that xcm message, so it all depends on the runtime if it can produce a message or not. If the runtime strictly required parachain to be registered then it will not produce a xcm message therefore the other chain won't intercept any message
