### ISSUE TITLE
support fellowship

### ISSUE THREAD

**Issue by brenzi** [AcalaNetwork/chopsticks#65]
The config file can override council and technical committee members. Would be great if the kusama config could be extended to override the fellowship.
I'd like to test the whitelisted_caller flow for gov2

**Comment by brenzi** [comment]
Could you add an example? Its not clear to me how I would make alice a single member of fellowship

**Comment by ermalkaleci** [comment]
<img width="694" alt="Screenshot 2022-12-02 at 10 31 18 AM" src="https://user-images.githubusercontent.com/3055344/205261397-01c0a5d4-c111-41d1-bc93-85723086de35.png">

check README (Optional) Pre-define/override storage using option --import-storage=storage.[json/yaml]. See example storage below.

it's a double map like Token::Accounts so it will be FellowshipCollective: { Members: <array of entries> } 

```
 FellowshipCollective: {
  Members: [
    [
      ["DSbhnaGBytDGRfZTmdcArzCL6T3HQ8gcZxWpF5gLBP6y1Qe"],
      {
        rank: 3
      }
    ]
  ]
}
```

**Comment by brenzi** [comment]
yes, this works. but unlike for council, it does not replace the the onchain fellowship, it just adds an account to it. Certain test scenarios may require to gain a majority of fellowship, so it would be nice if we could purge the fellowship and repalce it entirely

**Comment by ermalkaleci** [comment]
because council is storage_value and fellowship is storage_map. if you want to remove something just set null
`FellowshipCollective: {
  Members: [
    [
      ["DSbhnaGBytDGRfZTmdcArzCL6T3HQ8gcZxWpF5gLBP6y1Qe"],
      null
    ]
  ]
}`

**Comment by xlc** [comment]
I added the ability to clear storage map with #73 and updated kusama config with Alice as the solo fellowship member.
I didn't spend a lot of time testing so it will be great if you can help give it a play and see if it is working as expected @brenzi
