### ISSUE TITLE
Issues with Chopsticks and Kusama AssetHub

### ISSUE THREAD

**Issue by albertov19** [AcalaNetwork/chopsticks#654]
Hey, I'm getting the following error when running Chopsticks with AssetHub Kusama:

```
Error: NonRootBranchNodeWithNoValue
    at imports.wbg.__wbindgen_error_new (/home/purestake/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:633:19)
    at wasm://wasm/00974292:wasm-function[128]:0xc5ae9
    at wasm://wasm/00974292:wasm-function[356]:0x10e402
    at wasm://wasm/00974292:wasm-function[942]:0x1347c5
```
    
Any clues how can I get it to work?

**Comment by ermalkaleci** [comment]
have you tried cleaning db cache?

**Comment by ermalkaleci** [comment]
smoldot fails to decode proof

**Comment by ermalkaleci** [comment]
https://github.com/smol-dot/smoldot/issues/1633

**Comment by ermalkaleci** [comment]
@albertov19 use this branch https://github.com/AcalaNetwork/chopsticks/pull/655

**Comment by ermalkaleci** [comment]
@albertov19 I'm releasing a new beta version

**Comment by albertov19** [comment]
Thanks @ermalkaleci for the quick turnaround, when is this expected to be in the official Chopsticks version?

**Comment by ermalkaleci** [comment]
After we make sure beta is working correctly

**Comment by albertov19** [comment]
Hey @ermalkaleci I can confirm AssetHub Kusama now works
