### ISSUE TITLE
Allow shared chopsticks instance across browser tabs

### ISSUE THREAD

**Issue by qiweiii** [AcalaNetwork/chopsticks#674]
https://github.com/polkadot-js/apps/issues/10305#issue-2159074338

**Comment by qiweiii** [comment]
My idea is to use a [sharedWorker](https://github.com/GoogleChromeLabs/comlink?tab=readme-ov-file#sharedworker) when setup chain in fromEndpoint in `ChopsticksProvider`, and since comlink does not have an api for push messages, we can use [Broadcast_Channel_API](https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API) to publish message (which has a port property in message event that can be used by comlink.wrap). If other tab starts a fork, it ask in the channel with the endpoint, if other tab has a worker with the same rpc endpoint then respond. But there is another problem, we cannot create a worker inside a worker, need to handle how to create executor worker

**Comment by ermalkaleci** [comment]
Commented on pjs. This issue can be closed
