### ISSUE TITLE
Getting "slot number mismatch" error when calling any extrinsic in rococo asset hub

### ISSUE THREAD

**Issue by sebastianmontero** [AcalaNetwork/chopsticks#683]
Hi, I was trying to test a reserve asset transfer from rococo asset hub to a parachain, but chopsticks crashes with the following error:

![image](https://github.com/AcalaNetwork/chopsticks/assets/13155714/891cc7c3-9512-43e6-8919-4e0ad626eea6)

I then realised that it happens when calling any extrinsic on asset hub, why might this be? I have no issues calling extrinsics on the parachain.

The command I'm using is:
`xcm -r ../chopsticks-hashed/rococo.yml -p  ../chopsticks-hashed/md5.yml -p ../chopsticks-hashed/rococo-asset-hub.yml`

The files I'm using are:
 - https://github.com/hashed-io/chopsticks-hashed/blob/master/rococo.yml
 - https://github.com/hashed-io/chopsticks-hashed/blob/master/md5.yml
 - https://github.com/hashed-io/chopsticks-hashed/blob/master/rococo-asset-hub.yml

Thanks

**Comment by xlc** [comment]
what version are you using? can you try latest one as https://github.com/AcalaNetwork/chopsticks/pull/677 may fix your problem

**Comment by sebastianmontero** [comment]
Thanks @xlc! That worked!
