### ISSUE TITLE
Treasury pay out doesn't occur with proposals created using Chopsticks

### ISSUE THREAD

**Issue by CrackTheCode016** [AcalaNetwork/chopsticks#714]
I noticed that while _currently_ active (as in, deployed on Polkadot already), treasury proposals will result in a payout using chopsticks, doing so with proposals created within the chopsticks environment are approved but often have a "0 DOT" payout, and upon the spend period ends, do not credit the account from the treasury.

An example of this behavior: 

- I create a small tipper referendum to FERDIE for something like 100 DOT from the treasury using `spend local.`
- I use a script from [moonbeam](https://github.com/Moonsong-Labs/moonbeam-tools/blob/main/src/tools/fast-execute-chopstick-proposal.ts) to nudge and accelerate the proposal to a passing state,.
- The referenda is approved, but shows the payout as being 0 DOT via the treasury page on PJS.
- When the spend period is reached, the payout also doesn't happen.

**Comment by xlc** [comment]
Can you provide the precise steps to reproduce this issues? i.e. with the command you using, the transactions you sending.
Also some screenshots of the results you getting would be helpful.

**Comment by xlc** [comment]
stale
