### ISSUE TITLE
normal sealing mode

### ISSUE THREAD

**Issue by shunjizhan** [AcalaNetwork/chopsticks#737]
Currently it only supports "instant sealing" mode, where block production stops if there is no new tx. This works perfectly for most scenarios where we only care about state changes. 

However this has some small issues when running chopsticks as a long-running fork testnet, for example:
- if I want to test a contract that changes state every block, such as count down
- if I want to test a behavior where there are more than 1 tx in a block
- some toolings might not be compatible, such as subquery, it might think the chain has stopped

A "normal sealing" mode would be nice a have for the fork testnet, where the behavior is more consistent with the original chain. i.e produce block every configurable `X` seconds no matter if there is new transaction.

**Comment by ermalkaleci** [comment]
there's also the option to call RPC `dev_newBlock` every x seconds

**Comment by xlc** [comment]
duplicates of #101
