### ISSUE TITLE
Missing new hostfunction

### ISSUE THREAD

**Issue by Daanvdplas** [AcalaNetwork/chopsticks#738]
I'm aware of the fix made in #713 and its respective fix in Smoldot however I run into the error that an extrinsic can't be applied due to the missing host function `ext_storage_proof_size_storage_proof_size_version_1`:
![Screenshot 2024-04-17 at 11 08 47](https://github.com/AcalaNetwork/chopsticks/assets/93204684/d9f8702b-8e3a-4378-a811-ef9fd97b29f1)

I'm running latest version of chopsticks and I'm doing a runtime upgrade of my parachain from polkadot v1.8 to v1.9.

**Comment by ermalkaleci** [comment]
it is define so smoldot recognises it as a host function but is not implemented. It will return error when called
https://github.com/smol-dot/smoldot/pull/1742. This host function will default to u64:MAX. What exactly are you trying to do?
