### ISSUE TITLE
Override relay storage keys included in set_validation_data inherent

### ISSUE THREAD

**Issue by RomarQ** [AcalaNetwork/chopsticks#757]
The storage `paras > upgradeCooldowns` is part of the relay storage keys included with `set_validation_data` inherent. 

Is there currently a way to remove relay storages keys when testing a parachain with chopsticks?

**Comment by ermalkaleci** [comment]
https://github.com/paritytech/polkadot-sdk/blob/313fe0f9a277f27a4228634f0fb15a1c3fa21271/cumulus/client/parachain-inherent/src/lib.rs#L99-L123 I don't think it is included

**Comment by RomarQ** [comment]
You are right, it is the `upgrade_restriction_signal` storage.

Is there a way in chopsticks to change the value for that storage key?

**Comment by xlc** [comment]
it should be possible to add a new option to `dev_newBlock` to pass some parameters to the inherent builder

**Comment by ermalkaleci** [comment]
https://github.com/AcalaNetwork/chopsticks/blob/15ef2280951b1c93baa9239f4b32721b2085afff/packages/core/src/blockchain/inherent/parachain/validation-data.ts#L260-L269
this is how we manipulate relay-chain data

**Comment by RomarQ** [comment]
But can I override those externally without changing the in the chopsticks internals?

**Comment by RomarQ** [comment]
Ok, thanks.
