### ISSUE TITLE
latest release 0.12.0 is broken

### ISSUE THREAD

**Issue by ermalkaleci** [AcalaNetwork/chopsticks#770]
chopsticks package doesn't have @polkadot/api dependency 
<img width="370" alt="Screenshot 2024-06-03 at 10 58 28 AM" src="https://github.com/AcalaNetwork/chopsticks/assets/3055344/ea761b7a-f7c4-43eb-be6b-83261c11b1f6">

` code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ermal/.npm/_npx/c1c4d257924715f9/node_modules/@acala-network/chopsticks/dist/cjs/utils/fetch-storages.js',
    '/Users/ermal/.npm/_npx/c1c4d257924715f9/node_modules/@acala-network/chopsticks/dist/cjs/context.js',
    '/Users/ermal/.npm/_npx/c1c4d257924715f9/node_modules/@acala-network/chopsticks/dist/cjs/setup-with-server.js',
    '/Users/ermal/.npm/_npx/c1c4d257924715f9/node_modules/@acala-network/chopsticks/dist/cjs/index.js',
    '/Users/ermal/.npm/_npx/c1c4d257924715f9/node_modules/@acala-network/chopsticks/dist/cjs/cli.js',
    '/Users/ermal/.npm/_npx/c1c4d257924715f9/node_modules/@acala-network/chopsticks/chopsticks.cjs'
  ]`

**Comment by xlc** [comment]
looks like is due to https://github.com/AcalaNetwork/chopsticks/pull/764/files#diff-5ee6262753c038ef7e0ba7f03e1fc0d8440c717644a06e32a1ab1f8c9afafdf1R2
I guess we need some extra CI checks
