### ISSUE TITLE
Chopstics cannot process transactions with `CheckMetadataHash` extension

### ISSUE THREAD

**Issue by valentunn** [AcalaNetwork/chopsticks#779]
Steps to reproduce:

1. Fork Kusama
2. Apply 1.2.5 runtime upgrade https://github.com/polkadot-fellows/runtimes/releases/tag/v1.2.5
3. Try to transfer from Alice account via Polkadot.js

The same can be observed with `payment_queryFeeInfo` rpc call but not when fetching fee information via `state_call`

Guessing the potential solution, bumbing `polkadot-js/api` should help since recent version includes support for `CheckMetadataHash`

<img width="430" alt="image" src="https://github.com/AcalaNetwork/chopsticks/assets/70131744/0eb13811-00d5-4ff9-9cac-42703eb5008c">

**Comment by qiweiii** [comment]
I created a pr #781 that use latest polkadota/api, seems it works. Please check if it solves this issue

**Comment by ermalkaleci** [comment]
@qiweiii yes we just need to bump pjs/api. as long as tests pass it won't cause any harm to release a new version

**Comment by qiweiii** [comment]
Released 0.12.2
