### ISSUE TITLE
Log setting not respected

### ISSUE THREAD

**Issue by green-jay** [AcalaNetwork/chopsticks#785]
Adding `runtime-log-level: 5` to chain config doesn't increase detail of logs for Polkadot and system chains e.g. Asset Hub.
For parachains (e.g. Hydration) it generally works.

**Comment by ermalkaleci** [comment]
Polkadot runtimes are built with logs disabled. You need to provide a custom one with logs enabled

**Comment by green-jay** [comment]
> Polkadot runtimes are built with logs disabled. You need to provide a custom one with logs enabled

Got it, thanks. If there is no way around it, you can close the issue.

**Comment by ermalkaleci** [comment]
I can't close it. I don't have access.
