### ISSUE TITLE
XCM Message Targeting 2004 Shows Recipient as 1002

### ISSUE THREAD

**Issue by albertov19** [AcalaNetwork/chopsticks#802]
Hey I'm sending the following XCM message from AssetHub

![image](https://github.com/user-attachments/assets/fdee70d9-f86d-4204-90d5-2fca8654a2ae)

And when I check the Chopsticks Logs I see that it shows the recipient being 1002

![image](https://github.com/user-attachments/assets/5b9d60d6-5ce2-4f24-a6c6-d707d0a35ee8)

My Parachain (2004) is not receiving it also.

**Comment by xlc** [comment]
what asset is being transferred? are you trying to transfer ETH which the reserve chain will be BH?

**Comment by albertov19** [comment]
Yeah sorry I had to use another extrinsic. Worked like a charm after doing it the right way.
