### ISSUE TITLE
Error when fork Async Backing Enabling Runtime

### ISSUE THREAD

**Issue by sfffaaa** [AcalaNetwork/chopsticks#808]
Hi, we encountered a similar issue: https://github.com/AcalaNetwork/chopsticks/pull/743. However, the fix doesn't help in our case.

```
    app: "chopsticks"
                     runtime  ERROR: panicked at /home/jaypan/.cargo/git/checkouts/polkadot-sdk-d4b773be765ce22f/538d3a3/substrate/frame/aura/src/lib.rs:416:9:
assertion `left == right` failed: Timestamp slot must match `CurrentSlot`
  left: Slot(287413136)
 right: Slot(287413137)
[07:53:50.693] WARN (block-builder): Failed to apply inherents {} Error: wasm `unreachable` instruction executed
    app: "chopsticks"
file:///home/jaypan/Work/peaq/chopsticks/packages/core/src/blockchain/block-builder.ts:190
            throw new Error('Failed to apply inherents');
                  ^

Error: Failed to apply inherents
    at initNewBlock (file:///home/jaypan/Work/peaq/chopsticks/packages/core/src/blockchain/block-builder.ts:190:19)
    at async buildBlock (file:///home/jaypan/Work/peaq/chopsticks/packages/core/src/blockchain/block-builder.ts:297:44)
    at async #buildBlock (file:///home/jaypan/Work/peaq/chopsticks/packages/core/src/blockchain/txpool.ts:215:47)
    at async #buildBlockIfNeeded (file:///home/jaypan/Work/peaq/chopsticks/packages/core/src/blockchain/txpool.ts:199:13)
```

Is that related to https://github.com/paritytech/polkadot-sdk/pull/3211?

My command is this
```
yarn start -e wss://docker-test.peaq.network -w peaq_runtime.compact.compressed.wasm.peaq.v0.0.101

```
And the WASM code is [here](https://drive.google.com/file/d/1KVF21X61bEziKY_CeHMdrvURx72odFpX/view?usp=drive_link)

The version of WASM is based on polkadot-sdk 1.7.2

**Comment by ermalkaleci** [comment]
your problem seems to be missing aura runtime api to get slot duration and chopsticks is falling back to 12s block time

**Comment by sfffaaa** [comment]
Hi, thanks for replying. I'm checking about the aura runtime API (auraApi.slotDuration) and the return is 6000.
<img width="1327" alt="Screenshot 2024-08-25 at 13 48 03" src="https://github.com/user-attachments/assets/e94b1811-8973-4384-acb5-e4d857cc569c">

In my survey, it looks like [this](https://github.com/AcalaNetwork/chopsticks/blob/master/packages/core/src/blockchain/inherent/parachain/validation-data.ts#L134) didn't affect after writing, but I don't understand why

**Comment by ermalkaleci** [comment]
@sfffaaa ok I see. Chopsticks can't find aura storage and assuming there's no aura_runtime_api and it fallback to 12s block time

**Comment by sfffaaa** [comment]
Yep, you are right. I also found the solution and open the [MR](https://github.com/AcalaNetwork/chopsticks/pull/810)

**Comment by ermalkaleci** [comment]
I have this [PR](https://github.com/AcalaNetwork/chopsticks/pull/809) opened. I will apply a fix there

**Comment by sfffaaa** [comment]
Cool, that will be great! Thank you very much!
