### ISSUE TITLE
improve block building performance

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/chopsticks#83]
- [ ] bulk storage fetch
- [ ] For Kusama / Polkadot improve session change block handling somehow to avoid session related work, which reads a lot of storages

**Comment by ermalkaleci** [comment]
after #93 is merged we can start task with pre-key-value to avoid going back and forth for well known keys that are required to initialize block or execute transaction

**Comment by ermalkaleci** [comment]
in case those keys are not locally then it will be wise to fetch multi keys before starting the task
