### ISSUE TITLE
update polkadot.js version to latest

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/chopsticks#847]
after https://github.com/polkadot-js/api/issues/6010 is fixed and new version released, remove the resolutions and bump pjs to the new version

https://github.com/AcalaNetwork/chopsticks/blob/46f0713cae631a31f20d80fe33f4a4c6554e1e75/package.json#L12-L21

**Comment by soloking1412** [comment]
I can help remove the `resolutions`and update the polkadot.js to the latest version. I will ensure compatibility by testing the updated version thoroughly to confirm that all functionalities work as expected without any regressions.

**Comment by ermalkaleci** [comment]
already resolved
