### ISSUE TITLE
WASM Override in `chopsticks-core`

### ISSUE THREAD

**Issue by pandres95** [AcalaNetwork/chopsticks#857]
## Context

`wasm-override` is by far, one of the most useful utilities you can find on Chopsticks, allowing to build local testing frameworks by forking and overriding the runtime WASM on an existing testnet/livenet chain.

However, the fact that this option only exists on `setupWithServer` makes it hard to create integrations (e.g. to use it as a framework for E2E testing) that don't necessarily require exposing a port, or that might be affected by doing it so.

## Description

It would be useful to support a `wasmOverride` option on the `setup` method of `chopsticks-core`, in such a way this capability can be used on non-CLI usages of Chopsticks (like the library release of [`kreivo-sandbox`](https://github.com/virto-network/kreivo-sandbox), for example).

**Comment by ermalkaleci** [comment]
You can use `wasmOverride` util function however you like. It just takes the chain and wasm

**Comment by ermalkaleci** [comment]
Or you can just do `chain.head.setWasm(code)` 🙂

**Comment by pandres95** [comment]
The first option worked pretty well. I'll have this issue into consideration for future documenting myself. 😅 

Thanks so much.
