### ISSUE TITLE
Support `archive_unstable_call`

### ISSUE THREAD

**Issue by Tbaut** [AcalaNetwork/chopsticks#865]
While all the `archive_unstable_` were quite straightforward so far, I'd like to support another call we're using in Multix `archive_unstable_call` which we use to call the metadata_metaddata at a specific block hash:
```ts
client
  ._request<{
    result: HexString
  }>('archive_unstable_call', [blockHash, 'Metadata_metadata', ''])
  .then((x) => opaqueMetadata(x.result)[1])
```

Here's the implementation: https://github.com/paritytech/polkadot-sdk/pull/1582

**Comment by Tbaut** [comment]
Any pointer for this one?

**Comment by xlc** [comment]
looks like just an alias of `state_call`?
