### ISSUE TITLE
implement `api.rpc.payment.queryInfo`

### ISSUE THREAD

**Issue by shunjizhan** [AcalaNetwork/chopsticks#90]
this is the last piece missing for bodhi compatibility

**Comment by xlc** [comment]
this should be implemented on the bodhi side using state_call

**Comment by shunjizhan** [comment]
isn't it a standard substrate RPC that should be available for all chains?
<img width="687" alt="Screenshot 2022-12-15 at 10 38 48" src="https://user-images.githubusercontent.com/16548786/207759528-17352973-f8a2-4fee-8003-33b1307e560f.png">

**Comment by xlc** [comment]
kind of but not really. there is no RPC standard so there is no standard substrate RPC...

**Comment by xlc** [comment]
but basically we only want to implement RPC that's supported by substrate-connect
