### ISSUE TITLE
put/get for `0x` doesn't seem to work as expected

### ISSUE THREAD

**Issue by crystalin** [AcalaNetwork/chopsticks#97]
In our randomness inherent, we put an empty value to a storage item (used to ensure the inherent was set)
(see https://github.com/PureStake/moonbeam/blob/master/pallets/randomness/src/lib.rs#L258 for put and https://github.com/PureStake/moonbeam/blob/master/pallets/randomness/src/lib.rs#L306 for the check)

The logs are showing the value being set:
```
    4: [
      "0x7a414cb008e0e61e46722aa60abdd672e071d663aecfe81953e36656ddea98c6",
      "0x"
    ]
```
and retrieved later:
```
[11:30:41.067] TRACE (rpc-exec/23305): exec_storageGet
    blockHash: "0xb535900000000000000000000000000000000000000000000000000000000000"
    key: "0x7a414cb008e0e61e46722aa60abdd672e071d663aecfe81953e36656ddea98c6"
    value: "0x"
```

Howerver the runtime still crashes with
```
[ERROR] 11:30:41 Error: Error while executing Wasm VM: Trap: Unreachable
"panicked at 'Mandatory randomness inherent not included; InherentIncluded storage item is empty', /build/pallets/randomness/src/lib.rs:305:13"
```

**Comment by crystalin** [comment]
It seems to be related to the "default" value not being set. 
Changing `exec_storageGet` to contain:
```
    const value =
      key == '0x7a414cb008e0e61e46722aa60abdd672e071d663aecfe81953e36656ddea98c6' ? '0x00' : await block.get(key)
```
makes it produce the block correctly

(I tried using `return value == '0x' ? '0x00' : value` instead but that break other parts)

**Comment by ermalkaleci** [comment]
@crystalin I think you need to pass a default value

**Comment by ermalkaleci** [comment]
> @crystalin I think you need to pass a default value

I will take a look

**Comment by ermalkaleci** [comment]
I think I found the issue

**Comment by ermalkaleci** [comment]
should be fixed now
